//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import "EsMessage.h"
#import "EsMessageType.h"
#import "EsRequest.h"
#import "EsResponse.h"
#import "EsEvent.h"
#import "EsEntity.h"
#import "EsObject.h"
#import "ThriftAddBuddiesResponse.h"

/**
 * This is a response to an AddBuddiesRequest, detailing for each user listed
 in the request whether the user was added as a buddy or not.
 */
@interface EsAddBuddiesResponse : EsResponse {
@private
	BOOL buddiesAdded_set_;
	NSMutableArray* buddiesAdded_;
	BOOL buddiesNotAdded_set_;
	NSMutableArray* buddiesNotAdded_;
}

@property(strong,nonatomic) NSMutableArray* buddiesAdded;
@property(strong,nonatomic) NSMutableArray* buddiesNotAdded;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftAddBuddiesResponse*) toThrift;
- (id) newThrift;
@end
