//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import "EsMessage.h"
#import "EsMessageType.h"
#import "EsRequest.h"
#import "EsResponse.h"
#import "EsEvent.h"
#import "EsEntity.h"
#import "EsObject.h"
#import "ThriftGetGameTypesResponse.h"

/**
 * When a client sends a GetGameTypesRequest it leads to this response, which
 contains a list of all gameTypes currently registered with GameManager.
 */
@interface EsGetGameTypesResponse : EsResponse {
@private
	BOOL gameTypes_set_;
	NSMutableArray* gameTypes_;
}

/**
 * List of game types registered.
 */
@property(strong,nonatomic) NSMutableArray* gameTypes;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftGetGameTypesResponse*) toThrift;
- (id) newThrift;
@end
