//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import "EsMessage.h"
#import "EsMessageType.h"
#import "EsRequest.h"
#import "EsResponse.h"
#import "EsEvent.h"
#import "EsEntity.h"
#import "EsObject.h"
#import "ThriftGetGameTypesRequest.h"

/**
 * This request asks the server for a list of registered gametypes. 
 It leads to a a GetGameTypesResponse which contains the list.
 */
@interface EsGetGameTypesRequest : EsRequest {
@private
}


- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftGetGameTypesRequest*) toThrift;
- (id) newThrift;
@end
