/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"


@interface ThriftGetGameTypesResponse : NSObject <NSCoding> {
  NSArray * __gameTypes;

  BOOL __gameTypes_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=gameTypes, setter=setGameTypes:) NSArray * gameTypes;
#endif

- (id) initWithGameTypes: (NSArray *) gameTypes;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) gameTypes;
- (void) setGameTypes: (NSArray *) gameTypes;
- (BOOL) gameTypesIsSet;

@end

@interface ThriftGetGameTypesResponseConstants : NSObject {
}
@end
