//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import "EsDHPublicNumbersResponse.h"
#import "EsThriftUtil.h"

@implementation EsDHPublicNumbersResponse

@synthesize baseNumber = baseNumber_;
@synthesize primeNumber = primeNumber_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_DHPublicNumbers;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftDHPublicNumbersResponse* t = (ThriftDHPublicNumbersResponse*) thriftObject;
	if ([t baseNumberIsSet] && t.baseNumber != nil) {
		self.baseNumber = t.baseNumber;
	}
	if ([t primeNumberIsSet] && t.primeNumber != nil) {
		self.primeNumber = t.primeNumber;
	}
}

- (ThriftDHPublicNumbersResponse*) toThrift {
	ThriftDHPublicNumbersResponse* _t = [[ThriftDHPublicNumbersResponse alloc] init];;
	if (baseNumber_set_ && baseNumber_ != nil) {
		NSString* _baseNumber;
		_baseNumber = self.baseNumber;
		_t.baseNumber = _baseNumber;
	}
	if (primeNumber_set_ && primeNumber_ != nil) {
		NSString* _primeNumber;
		_primeNumber = self.primeNumber;
		_t.primeNumber = _primeNumber;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftDHPublicNumbersResponse alloc] init];
}

- (void) setBaseNumber: (NSString*) baseNumber {
	baseNumber_ = baseNumber;
	baseNumber_set_ = true;
}

- (void) setPrimeNumber: (NSString*) primeNumber {
	primeNumber_ = primeNumber;
	primeNumber_set_ = true;
}


@end
