//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import "EsGetGameTypesRequest.h"
#import "EsThriftUtil.h"

@implementation EsGetGameTypesRequest


- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_GetGameTypesRequest;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
}

- (ThriftGetGameTypesRequest*) toThrift {
	ThriftGetGameTypesRequest* _t = [[ThriftGetGameTypesRequest alloc] init];;
	return _t;
}

- (id) newThrift {
	return [[ThriftGetGameTypesRequest alloc] init];
}


@end
