/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"


#import "ThriftGetGameTypesResponse.h"


@implementation ThriftGetGameTypesResponseConstants
+ (void) initialize {
}
@end

@implementation ThriftGetGameTypesResponse

- (id) initWithGameTypes: (NSArray *) gameTypes
{
  self = [super init];
  __gameTypes = gameTypes;
  __gameTypes_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"gameTypes"])
  {
    __gameTypes = [decoder decodeObjectForKey: @"gameTypes"];
    __gameTypes_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__gameTypes_isset)
  {
    [encoder encodeObject: __gameTypes forKey: @"gameTypes"];
  }
}


- (NSArray *) gameTypes {
  return __gameTypes;
}

- (void) setGameTypes: (NSArray *) gameTypes {
  __gameTypes = gameTypes;
  __gameTypes_isset = YES;
}

- (BOOL) gameTypesIsSet {
  return __gameTypes_isset;
}

- (void) unsetGameTypes {
  __gameTypes = nil;
  __gameTypes_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_LIST) {
          int _size0;
          [inProtocol readListBeginReturningElementType: NULL size: &_size0];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            NSString * _elem2 = [inProtocol readString];
            [fieldValue addObject: _elem2];
          }
          [inProtocol readListEnd];
          [self setGameTypes: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftGetGameTypesResponse"];
  if (__gameTypes_isset) {
    if (__gameTypes != nil) {
      [outProtocol writeFieldBeginWithName: @"gameTypes" type: TType_LIST fieldID: 1];
      {
        [outProtocol writeListBeginWithElementType: TType_STRING size: [__gameTypes count]];
        for (NSUInteger i4 = 0; i4 < [__gameTypes count]; i4++)
        {
          [outProtocol writeString: [__gameTypes objectAtIndex: i4]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftGetGameTypesResponse("];
  [ms appendString: @"gameTypes:"];
  [ms appendFormat: @"%@", __gameTypes];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

